app = "mdcatemy" 
primary_region = "bom"

[build]

[env]
  MODE = 'prod'
  PORT = '3000'
  JWT_SIGN_SECRET = '[i)CyE$+2-WICwgOIU.g-bs/zqj3Q6wt(B)cE9zylZuyfjil9b'
  PASSWORD_HASH_SECRET = 'srj&N^U_F[,1Qf.z(zx_v^es)V4#sVe1oLbJe(;enPxRkdXydy'
  DATABASE_USERNAME = 'postgres'
  DATABASE_PASSWORD = 'jLOSTCqidB0FRf6y'
  DATABASE_HOST = 'db.jhmtchfcwwihhzrnkmds.supabase.co'
  DATABASE_PORT = '5432'
  DATABASE_NAME = 'postgres'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "1   gb"

[[mounts]]
  source = "receipts_data"
  destination = "/app/receipts"
