app = "mdcatemy"
primary_region = "bom"

[env]
  DATABASE_HOST = "db.jhmtchfcwwihhzrnkmds.supabase.co"
  DATABASE_NAME = "postgres"
  DATABASE_PASSWORD = "jLOSTCqidB0FRf6y"
  DATABASE_PORT = "5432"
  DATABASE_USERNAME = "postgres"
  JWT_SIGN_SECRET = "[i)CyE$+2-WICwgOIU.g-bs/zqj3Q6wt(B)cE9zylZuyfjil9b"
  MODE = "prod"
  PASSWORD_HASH_SECRET = "srj&N^U_F[,1Qf.z(zx_v^es)V4#sVe1oLbJe(;enPxRkdXydy"
  PORT = "3000"

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 3000
  min_machines_running = 1

[[mounts]]
  destination = "/app/receipts"
  source = "receipts_data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1