name: CI and Deploy QuizBuilder Mini

on:
  push:
    branches:
      - quizbuilder-demo

jobs:
  ci-checks:
    name: CI - Build and Validate Application
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./quizbuilder-mini

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required project files
        run: |
          test -f docker-compose.yml
          test -f backend/Dockerfile
          test -f frontend/Dockerfile
          test -f backend/schema.sql
          test -f backend/db/seed.sql

      - name: Build Docker Compose services
        run: docker compose build

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Wait for containers to initialize
        run: sleep 25

      - name: Show running containers
        run: docker ps

      - name: Show Docker Compose service status
        run: docker compose ps

      - name: Test PostgreSQL container health
        run: |
          docker inspect --format='{{.State.Health.Status}}' quizmini_db | grep healthy

      - name: Test backend API
        run: |
          curl --fail http://localhost:3000/api/v1/subjects

      - name: Test frontend response
        run: |
          curl --fail http://localhost:8080

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down -v

  deploy:
    name: CD - Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: ci-checks

    steps:
      - name: Deploy on EC2 using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/MDCATemy
            git checkout quizbuilder-demo
            git pull origin quizbuilder-demo

            cd quizbuilder-mini
            docker-compose down
            docker-compose up --build -d
            docker ps