name: Deploy QuizBuilder Mini

on:
  push:
    branches:
      - quizbuilder-demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2 using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/MDCATemy
            git checkout quizbuilder-demo
            git pull origin quizbuilder-demo

            cd quizbuilder-mini
            docker-compose down
            docker-compose up --build -d
            docker ps